name: Simple test

on: 
  push: ~
  workflow_dispatch: ~

jobs: 
  runTest:
    name: execute simple test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref: ${{ github.sha }}

      - name: Install deps
        working-directory: src
        run: npm i

      - name: Run tests
        run: npm run test
