name: Test application

on: 
  push: ~
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch: ~

jobs: 
  runTest:
    name: execute test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref: ${{ github.sha }}

      - name: Create .env file
        run: |
          echo HOST=${{ secrets.HOST }} >> ./src/.env
          echo DATABASE=${{ secrets.DATABASE }} >> ./src/.env
          echo DB_PORT=${{ secrets.DB_PORT }} >> ./src/.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ./src/.env
          echo PASSWORD=${{ secrets.PASSWORD }} >> ./src/.env
          echo PORT=${{ secrets.PORT }} >> ./src/.env
          echo SECRET=${{ secrets.SECRET }} >> ./src/.env
          echo USER=${{ secrets.USER }} >> ./src/.env

      - name: Install deps
        working-directory: ./src
        run: npm i

      - name: Run model tests
        run: npm run test:models
        working-directory: ./src

      - name: Run route tests
        run: npm run test:routes
        working-directory: ./src
